# Configuração EasyPanel para Kmiza27 Chatbot
# Este arquivo define volumes persistentes para uploads

services:
  backend:
    image: kmiza27/backend:latest
    ports:
      - "3001:3001"
    volumes:
      # Volume persistente para uploads - IMPORTANTE!
      - /data/kmiza27/uploads:/app/uploads
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      EVOLUTION_API_URL: ${EVOLUTION_API_URL}
      EVOLUTION_API_KEY: ${EVOLUTION_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: kmiza27/frontend:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# Volumes persistentes
volumes:
  uploads_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/kmiza27/uploads 