-- Inserir times populares do futebol brasileiro
INSERT INTO teams (name, slug, full_name, short_name, stadium, city, state, founded_year) VALUES
-- Times da Série A
('Flamengo', 'flamengo', 'Clube de Regatas do Flamengo', 'FLA', 'Maracanã', 'Rio de Janeiro', 'RJ', 1895),
('Palmeiras', 'palmeiras', 'Sociedade Esportiva Palmeiras', 'PAL', 'Allianz Parque', 'São Paulo', 'SP', 1914),
('Fluminense', 'fluminense', 'Fluminense Football Club', 'FLU', 'Maracanã', 'Rio de Janeiro', 'RJ', 1902),
('Corinthians', 'corinthians', 'Sport Club Corinthians Paulista', 'COR', 'Neo Química Arena', 'São Paulo', 'SP', 1910),
('Athletico-PR', 'athletico-pr', 'Club Athletico Paranaense', 'CAP', 'Arena da Baixada', 'Curitiba', 'PR', 1924),
('Atlético-MG', 'atletico-mg', 'Clube Atlético Mineiro', 'CAM', 'Arena MRV', 'Belo Horizonte', 'MG', 1908),
('Fortaleza', 'fortaleza', 'Fortaleza Esporte Clube', 'FOR', 'Arena Castelão', 'Fortaleza', 'CE', 1918),
('São Paulo', 'sao-paulo', 'São Paulo Futebol Clube', 'SAO', 'Morumbi', 'São Paulo', 'SP', 1930),
('Botafogo', 'botafogo', 'Botafogo de Futebol e Regatas', 'BOT', 'Estádio Nilton Santos', 'Rio de Janeiro', 'RJ', 1894),
('Bragantino', 'bragantino', 'Red Bull Bragantino', 'RBB', 'Estádio Nabi Abi Chedid', 'Bragança Paulista', 'SP', 1928),
('Santos', 'santos', 'Santos Futebol Clube', 'SAN', 'Vila Belmiro', 'Santos', 'SP', 1912),
('Grêmio', 'gremio', 'Grêmio Foot-Ball Porto Alegrense', 'GRE', 'Arena do Grêmio', 'Porto Alegre', 'RS', 1903),
('Cruzeiro', 'cruzeiro', 'Cruzeiro Esporte Clube', 'CRU', 'Mineirão', 'Belo Horizonte', 'MG', 1921),
('Internacional', 'internacional', 'Sport Club Internacional', 'INT', 'Beira-Rio', 'Porto Alegre', 'RS', 1909),
('Vasco', 'vasco', 'Club de Regatas Vasco da Gama', 'VAS', 'São Januário', 'Rio de Janeiro', 'RJ', 1898),
('Bahia', 'bahia', 'Esporte Clube Bahia', 'BAH', 'Arena Fonte Nova', 'Salvador', 'BA', 1931),
('Goiás', 'goias', 'Goiás Esporte Clube', 'GOI', 'Serrinha', 'Goiânia', 'GO', 1943),
('Coritiba', 'coritiba', 'Coritiba Foot Ball Club', 'CFC', 'Couto Pereira', 'Curitiba', 'PR', 1909),
('América-MG', 'america-mg', 'América Futebol Clube', 'AME', 'Independência', 'Belo Horizonte', 'MG', 1912),
('Cuiabá', 'cuiaba', 'Cuiabá Esporte Clube', 'CUI', 'Arena Pantanal', 'Cuiabá', 'MT', 2001),
-- Times da Série B populares
('Sport', 'sport', 'Sport Club do Recife', 'SPT', 'Ilha do Retiro', 'Recife', 'PE', 1905),
('Ceará', 'ceara', 'Ceará Sporting Club', 'CEA', 'Arena Castelão', 'Fortaleza', 'CE', 1914),
('Ponte Preta', 'ponte-preta', 'Associação Atlética Ponte Preta', 'PON', 'Moisés Lucarelli', 'Campinas', 'SP', 1900),
('Guarani', 'guarani', 'Guarani Futebol Clube', 'GUA', 'Brinco de Ouro', 'Campinas', 'SP', 1911),
('Avaí', 'avai', 'Avaí Futebol Clube', 'AVA', 'Ressacada', 'Florianópolis', 'SC', 1923),
('Chapecoense', 'chapecoense', 'Associação Chapecoense de Futebol', 'CHA', 'Arena Condá', 'Chapecó', 'SC', 1973),
('CRB', 'crb', 'Clube de Regatas Brasil', 'CRB', 'Rei Pelé', 'Maceió', 'AL', 1912),
('Vila Nova', 'vila-nova', 'Vila Nova Futebol Clube', 'VIL', 'Onésio Brasileiro Alvarenga', 'Goiânia', 'GO', 1943),
('Juventude', 'juventude', 'Esporte Clube Juventude', 'JUV', 'Alfredo Jaconi', 'Caxias do Sul', 'RS', 1913),
('Novorizontino', 'novorizontino', 'Novorizontino', 'NOV', 'Jorge Ismael de Biasi', 'Novo Horizonte', 'SP', 1973); 