import { MigrationInterface, QueryRunner } from "typeorm";

export class AddPlayerStatsToMatches1749516836585 implements MigrationInterface {
    name = 'AddPlayerStatsToMatches1749516836585'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "rounds" DROP CONSTRAINT "rounds_competition_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "player_team_history" DROP CONSTRAINT "fk_player_team_history_player"`);
        await queryRunner.query(`ALTER TABLE "player_team_history" DROP CONSTRAINT "fk_player_team_history_team"`);
        await queryRunner.query(`ALTER TABLE "cards" DROP CONSTRAINT "fk_cards_match"`);
        await queryRunner.query(`ALTER TABLE "cards" DROP CONSTRAINT "fk_cards_player"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "fk_goals_player"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "goals_match_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "goals_team_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" DROP CONSTRAINT "match_broadcasts_match_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" DROP CONSTRAINT "match_broadcasts_channel_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "matches_competition_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "matches_round_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "matches_home_team_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "matches_away_team_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "matches_stadium_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "fk_matches_qualified_team"`);
        await queryRunner.query(`ALTER TABLE "competition_teams" DROP CONSTRAINT "competition_teams_competition_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "competition_teams" DROP CONSTRAINT "competition_teams_team_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "fk_teams_stadium_id"`);
        await queryRunner.query(`ALTER TABLE "chatbot_conversations" DROP CONSTRAINT "chatbot_conversations_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP CONSTRAINT "fk_notification_deliveries_notification"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP CONSTRAINT "fk_notification_deliveries_user"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_match_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_favorite_team_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_match_broadcasts_match_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_matches_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_matches_teams"`);
        await queryRunner.query(`DROP INDEX "public"."idx_matches_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_competition_teams"`);
        await queryRunner.query(`DROP INDEX "public"."idx_teams_stadium_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_chatbot_conv_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notification_deliveries_notification_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notification_deliveries_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notification_deliveries_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_send_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_phone"`);
        await queryRunner.query(`ALTER TABLE "competition_teams" DROP CONSTRAINT "competition_teams_competition_id_team_id_key"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP COLUMN "player_name"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP COLUMN "is_penalty"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP COLUMN "is_own_goal"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP COLUMN "video_url"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "home_yellow_cards"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "away_yellow_cards"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "home_red_cards"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "away_red_cards"`);
        await queryRunner.query(`ALTER TABLE "competitions" DROP COLUMN "tiebreaker_criteria"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP COLUMN "stadium"`);
        await queryRunner.query(`ALTER TABLE "players" ADD "state" character varying(50) DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "home_team_player_stats" jsonb`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "away_team_player_stats" jsonb`);
        await queryRunner.query(`ALTER TABLE "teams" ADD "short_code" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "rounds" ALTER COLUMN "is_current" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rounds" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rounds" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "stadiums" ALTER COLUMN "country" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stadiums" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stadiums" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "match_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "player_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "match_date"`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "match_date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "group_name"`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "group_name" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "phase"`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "phase" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "leg" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."leg" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."tie_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."home_aggregate_score" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."away_aggregate_score" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."qualified_team_id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "points" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "played" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "won" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "drawn" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "lost" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "goals_for" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "goals_against" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" DROP COLUMN "goal_difference"`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "database" = $3 AND "schema" = $4 AND "table" = $5`, ["GENERATED_COLUMN","goal_difference","kmiza27","public","competition_teams"]);
        await queryRunner.query(`ALTER TABLE "competition_teams" ADD "goal_difference" integer GENERATED ALWAYS AS (goals_for - goals_against) STORED NOT NULL`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES ($1, $2, $3, $4, $5, $6)`, ["kmiza27","public","competition_teams","GENERATED_COLUMN","goal_difference","goals_for - goals_against"]);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "country" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "chatbot_conversations" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chatbot_conversations" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP COLUMN "phone_number"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD "phone_number" character varying NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."delivery_status" RENAME TO "delivery_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notification_deliveries_status_enum" AS ENUM('pending', 'sending', 'delivered', 'failed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "status" TYPE "public"."notification_deliveries_status_enum" USING "status"::"text"::"public"."notification_deliveries_status_enum"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."delivery_status_old"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP COLUMN "whatsapp_message_id"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD "whatsapp_message_id" character varying`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "retry_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "is_sent" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."notification_send_status" RENAME TO "notification_send_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_send_status_enum" AS ENUM('draft', 'queued', 'sending', 'paused', 'completed', 'cancelled', 'failed')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "send_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "send_status" TYPE "public"."notifications_send_status_enum" USING "send_status"::"text"::"public"."notifications_send_status_enum"`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "send_status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."notification_send_status_old"`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "send_status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "total_recipients" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "sent_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "delivered_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "failed_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_admin" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "whatsapp_status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "system_settings" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "system_settings" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "system_settings" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "system_settings" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bot_configs" DROP CONSTRAINT "bot_configs_key_key"`);
        await queryRunner.query(`ALTER TABLE "bot_configs" DROP COLUMN "key"`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ADD "key" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ADD CONSTRAINT "UQ_b9dee26d13101a3dae7d232be5c" UNIQUE ("key")`);
        await queryRunner.query(`ALTER TABLE "bot_configs" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "bot_configs" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ADD "type" character varying NOT NULL DEFAULT 'string'`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ADD CONSTRAINT "UQ_eb3390d51aa9d9bf91a9a535357" UNIQUE ("competition_id", "team_id")`);
        await queryRunner.query(`ALTER TABLE "rounds" ADD CONSTRAINT "FK_a2afd93eef9019af00e5b0750bd" FOREIGN KEY ("competition_id") REFERENCES "competitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_team_history" ADD CONSTRAINT "FK_6718d122f4edf2f52421d8c11f6" FOREIGN KEY ("player_id") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_team_history" ADD CONSTRAINT "FK_7c37895964aa8abdaa37b36416f" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cards" ADD CONSTRAINT "FK_2b450d490a8af8790eb36a8bf64" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cards" ADD CONSTRAINT "FK_fba7c30be9d95ef283b044dcacb" FOREIGN KEY ("player_id") REFERENCES "players"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "FK_2f038c72761fa3e145e65388841" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "FK_7e801455fbac183f51a43b2d099" FOREIGN KEY ("player_id") REFERENCES "players"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "FK_722fcbb0807108f33384bba330f" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" ADD CONSTRAINT "FK_0f4f26a2d7a835aa6083862f0b3" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" ADD CONSTRAINT "FK_4fe688627a700fb47346ef5629f" FOREIGN KEY ("channel_id") REFERENCES "channels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_dc604f895a134adedbbf5bf405d" FOREIGN KEY ("competition_id") REFERENCES "competitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_59709772e5280108190154b7db1" FOREIGN KEY ("round_id") REFERENCES "rounds"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_bb25f11ea6fa78b344a68923769" FOREIGN KEY ("home_team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_e457f057d971e464c1ebf6378c5" FOREIGN KEY ("away_team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_f78a661415b0c75f087c6d026be" FOREIGN KEY ("stadium_id") REFERENCES "stadiums"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_6536ad8c674c5bf7e66f1cb3723" FOREIGN KEY ("qualified_team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ADD CONSTRAINT "FK_56f690272a10f500a7811730172" FOREIGN KEY ("competition_id") REFERENCES "competitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ADD CONSTRAINT "FK_98f4fb4f17e452cd23e9eecfd38" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "FK_5bb52f9ca6581157f87047dcaee" FOREIGN KEY ("stadium_id") REFERENCES "stadiums"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chatbot_conversations" ADD CONSTRAINT "FK_04587ca7b98d66cb1684d38b3b2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD CONSTRAINT "FK_435486b970fffc3e33a7450ee97" FOREIGN KEY ("notification_id") REFERENCES "notifications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD CONSTRAINT "FK_9fcd0b72070848cc484af6bc1ea" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_e74bbfb772dce73fb1de5e27a7e" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_cb0dbc4d8cc4e1a72df06890822" FOREIGN KEY ("favorite_team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_cb0dbc4d8cc4e1a72df06890822"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_e74bbfb772dce73fb1de5e27a7e"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP CONSTRAINT "FK_9fcd0b72070848cc484af6bc1ea"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP CONSTRAINT "FK_435486b970fffc3e33a7450ee97"`);
        await queryRunner.query(`ALTER TABLE "chatbot_conversations" DROP CONSTRAINT "FK_04587ca7b98d66cb1684d38b3b2"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "FK_5bb52f9ca6581157f87047dcaee"`);
        await queryRunner.query(`ALTER TABLE "competition_teams" DROP CONSTRAINT "FK_98f4fb4f17e452cd23e9eecfd38"`);
        await queryRunner.query(`ALTER TABLE "competition_teams" DROP CONSTRAINT "FK_56f690272a10f500a7811730172"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_6536ad8c674c5bf7e66f1cb3723"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_f78a661415b0c75f087c6d026be"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_e457f057d971e464c1ebf6378c5"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_bb25f11ea6fa78b344a68923769"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_59709772e5280108190154b7db1"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_dc604f895a134adedbbf5bf405d"`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" DROP CONSTRAINT "FK_4fe688627a700fb47346ef5629f"`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" DROP CONSTRAINT "FK_0f4f26a2d7a835aa6083862f0b3"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "FK_722fcbb0807108f33384bba330f"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "FK_7e801455fbac183f51a43b2d099"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "FK_2f038c72761fa3e145e65388841"`);
        await queryRunner.query(`ALTER TABLE "cards" DROP CONSTRAINT "FK_fba7c30be9d95ef283b044dcacb"`);
        await queryRunner.query(`ALTER TABLE "cards" DROP CONSTRAINT "FK_2b450d490a8af8790eb36a8bf64"`);
        await queryRunner.query(`ALTER TABLE "player_team_history" DROP CONSTRAINT "FK_7c37895964aa8abdaa37b36416f"`);
        await queryRunner.query(`ALTER TABLE "player_team_history" DROP CONSTRAINT "FK_6718d122f4edf2f52421d8c11f6"`);
        await queryRunner.query(`ALTER TABLE "rounds" DROP CONSTRAINT "FK_a2afd93eef9019af00e5b0750bd"`);
        await queryRunner.query(`ALTER TABLE "competition_teams" DROP CONSTRAINT "UQ_eb3390d51aa9d9bf91a9a535357"`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ALTER COLUMN "active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bot_configs" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ADD "type" character varying(50) DEFAULT 'string'`);
        await queryRunner.query(`ALTER TABLE "bot_configs" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ADD "description" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "bot_configs" DROP CONSTRAINT "UQ_b9dee26d13101a3dae7d232be5c"`);
        await queryRunner.query(`ALTER TABLE "bot_configs" DROP COLUMN "key"`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ADD "key" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ADD CONSTRAINT "bot_configs_key_key" UNIQUE ("key")`);
        await queryRunner.query(`ALTER TABLE "system_settings" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "system_settings" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "system_settings" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "system_settings" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "whatsapp_status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_admin" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "failed_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "delivered_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "sent_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "total_recipients" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "send_status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."notification_send_status_old" AS ENUM('draft', 'queued', 'sending', 'paused', 'completed', 'cancelled', 'failed')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "send_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "send_status" TYPE "public"."notification_send_status_old" USING "send_status"::"text"::"public"."notification_send_status_old"`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "send_status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."notifications_send_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_send_status_old" RENAME TO "notification_send_status"`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "is_sent" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "retry_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP COLUMN "whatsapp_message_id"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD "whatsapp_message_id" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."delivery_status_old" AS ENUM('pending', 'sending', 'delivered', 'failed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "status" TYPE "public"."delivery_status_old" USING "status"::"text"::"public"."delivery_status_old"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."notification_deliveries_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."delivery_status_old" RENAME TO "delivery_status"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP COLUMN "phone_number"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD "phone_number" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chatbot_conversations" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "chatbot_conversations" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "country" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "database" = $3 AND "schema" = $4 AND "table" = $5`, ["GENERATED_COLUMN","goal_difference","kmiza27","public","competition_teams"]);
        await queryRunner.query(`ALTER TABLE "competition_teams" DROP COLUMN "goal_difference"`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES ($1, $2, $3, $4, $5, $6)`, ["kmiza27","public","competition_teams","GENERATED_COLUMN","goal_difference",""]);
        await queryRunner.query(`ALTER TABLE "competition_teams" ADD "goal_difference" integer`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "goals_against" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "goals_for" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "lost" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "drawn" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "won" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "played" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "points" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."qualified_team_id" IS 'ID do time que se classificou após o confronto'`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."away_aggregate_score" IS 'Placar agregado do time visitante (soma dos dois jogos)'`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."home_aggregate_score" IS 'Placar agregado do time mandante (soma dos dois jogos)'`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."tie_id" IS 'UUID que agrupa jogos de ida e volta do mesmo confronto'`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."leg" IS 'Indica se é jogo de ida (1) ou volta (2) em confrontos mata-mata'`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "leg" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "phase"`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "phase" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "group_name"`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "group_name" character varying(10)`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "match_date"`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "match_date" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "type" SET DEFAULT 'other'`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "player_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "match_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stadiums" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "stadiums" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stadiums" ALTER COLUMN "country" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rounds" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "rounds" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rounds" ALTER COLUMN "is_current" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "teams" DROP COLUMN "short_code"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "away_team_player_stats"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "home_team_player_stats"`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "state"`);
        await queryRunner.query(`ALTER TABLE "teams" ADD "stadium" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "competitions" ADD "tiebreaker_criteria" jsonb`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "away_red_cards" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "home_red_cards" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "away_yellow_cards" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "home_yellow_cards" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "goals" ADD "video_url" text`);
        await queryRunner.query(`ALTER TABLE "goals" ADD "is_own_goal" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "goals" ADD "is_penalty" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "goals" ADD "player_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ADD CONSTRAINT "competition_teams_competition_id_team_id_key" UNIQUE ("competition_id", "team_id")`);
        await queryRunner.query(`CREATE INDEX "idx_users_phone" ON "users" ("phone_number") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_user" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_send_status" ON "notifications" ("send_status") `);
        await queryRunner.query(`CREATE INDEX "idx_notification_deliveries_status" ON "notification_deliveries" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_notification_deliveries_user_id" ON "notification_deliveries" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_notification_deliveries_notification_id" ON "notification_deliveries" ("notification_id") `);
        await queryRunner.query(`CREATE INDEX "idx_chatbot_conv_user" ON "chatbot_conversations" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_teams_stadium_id" ON "teams" ("stadium_id") `);
        await queryRunner.query(`CREATE INDEX "idx_competition_teams" ON "competition_teams" ("competition_id", "team_id") `);
        await queryRunner.query(`CREATE INDEX "idx_matches_date" ON "matches" ("match_date") `);
        await queryRunner.query(`CREATE INDEX "idx_matches_teams" ON "matches" ("away_team_id", "home_team_id") `);
        await queryRunner.query(`CREATE INDEX "idx_matches_status" ON "matches" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_match_broadcasts_match_id" ON "match_broadcasts" ("match_id") `);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_favorite_team_id_fkey" FOREIGN KEY ("favorite_team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_match_id_fkey" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD CONSTRAINT "fk_notification_deliveries_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD CONSTRAINT "fk_notification_deliveries_notification" FOREIGN KEY ("notification_id") REFERENCES "notifications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chatbot_conversations" ADD CONSTRAINT "chatbot_conversations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "fk_teams_stadium_id" FOREIGN KEY ("stadium_id") REFERENCES "stadiums"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ADD CONSTRAINT "competition_teams_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ADD CONSTRAINT "competition_teams_competition_id_fkey" FOREIGN KEY ("competition_id") REFERENCES "competitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "fk_matches_qualified_team" FOREIGN KEY ("qualified_team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "matches_stadium_id_fkey" FOREIGN KEY ("stadium_id") REFERENCES "stadiums"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "matches_away_team_id_fkey" FOREIGN KEY ("away_team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "matches_home_team_id_fkey" FOREIGN KEY ("home_team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "matches_round_id_fkey" FOREIGN KEY ("round_id") REFERENCES "rounds"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "matches_competition_id_fkey" FOREIGN KEY ("competition_id") REFERENCES "competitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" ADD CONSTRAINT "match_broadcasts_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "channels"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" ADD CONSTRAINT "match_broadcasts_match_id_fkey" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "goals_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "goals_match_id_fkey" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "fk_goals_player" FOREIGN KEY ("player_id") REFERENCES "players"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cards" ADD CONSTRAINT "fk_cards_player" FOREIGN KEY ("player_id") REFERENCES "players"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cards" ADD CONSTRAINT "fk_cards_match" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_team_history" ADD CONSTRAINT "fk_player_team_history_team" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_team_history" ADD CONSTRAINT "fk_player_team_history_player" FOREIGN KEY ("player_id") REFERENCES "players"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rounds" ADD CONSTRAINT "rounds_competition_id_fkey" FOREIGN KEY ("competition_id") REFERENCES "competitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
