import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateSimulationHistoryTable1755379382888 implements MigrationInterface {
    name = 'CreateSimulationHistoryTable1755379382888'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "rounds" DROP CONSTRAINT "rounds_competition_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "player_team_history" DROP CONSTRAINT "fk_player_team_history_team"`);
        await queryRunner.query(`ALTER TABLE "player_team_history" DROP CONSTRAINT "fk_player_team_history_player"`);
        await queryRunner.query(`ALTER TABLE "cards" DROP CONSTRAINT "fk_cards_player"`);
        await queryRunner.query(`ALTER TABLE "cards" DROP CONSTRAINT "fk_cards_match"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "goals_team_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "goals_match_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "fk_goals_player"`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" DROP CONSTRAINT "match_broadcasts_match_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" DROP CONSTRAINT "match_broadcasts_channel_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "matches_stadium_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "matches_round_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "matches_home_team_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "matches_competition_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "matches_away_team_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "fk_matches_qualified_team"`);
        await queryRunner.query(`ALTER TABLE "competition_teams" DROP CONSTRAINT "competition_teams_team_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "competition_teams" DROP CONSTRAINT "competition_teams_competition_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "fk_teams_stadium_id"`);
        await queryRunner.query(`ALTER TABLE "chatbot_conversations" DROP CONSTRAINT "chatbot_conversations_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP CONSTRAINT "fk_notification_deliveries_user"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP CONSTRAINT "fk_notification_deliveries_notification"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_match_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_favorite_team_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pool_matches" DROP CONSTRAINT "pool_matches_match_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pool_matches" DROP CONSTRAINT "pool_matches_pool_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pool_participants" DROP CONSTRAINT "pool_participants_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pool_participants" DROP CONSTRAINT "pool_participants_pool_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" DROP CONSTRAINT "pool_predictions_match_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" DROP CONSTRAINT "pool_predictions_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" DROP CONSTRAINT "pool_predictions_pool_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pools" DROP CONSTRAINT "pools_created_by_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pools" DROP CONSTRAINT "pools_round_id_fkey"`);
        // Comentar constraints que não existem
        // await queryRunner.query(`ALTER TABLE "pools" DROP CONSTRAINT "pools_competition_id_fkey"`);
        // await queryRunner.query(`ALTER TABLE "international_teams" DROP CONSTRAINT "FK_international_teams_team_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_match_broadcasts_match_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_matches_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_matches_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_matches_teams"`);
        await queryRunner.query(`DROP INDEX "public"."idx_competition_teams"`);
        await queryRunner.query(`DROP INDEX "public"."idx_teams_stadium_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_item_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_section_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_chatbot_conv_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notification_deliveries_notification_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notification_deliveries_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notification_deliveries_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_send_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_phone"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pool_matches_pool"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pool_matches_match"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pool_participants_pool"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pool_participants_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pool_participants_score"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pool_predictions_pool"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pool_predictions_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pool_predictions_match"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pools_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pools_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pools_created_by"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pools_public"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_international_teams_team_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_international_teams_display_order"`);
        await queryRunner.query(`ALTER TABLE "competition_teams" DROP CONSTRAINT "competition_teams_competition_id_team_id_key"`);
        await queryRunner.query(`ALTER TABLE "pool_matches" DROP CONSTRAINT "pool_matches_pool_id_match_id_key"`);
        await queryRunner.query(`ALTER TABLE "pool_participants" DROP CONSTRAINT "pool_participants_pool_id_user_id_key"`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" DROP CONSTRAINT "pool_predictions_pool_id_user_id_match_id_key"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP COLUMN "is_penalty"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP COLUMN "is_own_goal"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP COLUMN "video_url"`);
        await queryRunner.query(`ALTER TABLE "competitions" DROP COLUMN "tiebreaker_criteria"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP COLUMN "stadium"`);
        await queryRunner.query(`ALTER TABLE "pool_matches" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" DROP COLUMN "away_score_prediction"`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" DROP COLUMN "home_score_prediction"`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" DROP COLUMN "score"`);
        await queryRunner.query(`ALTER TABLE "pools" DROP COLUMN "competition_id"`);
        await queryRunner.query(`ALTER TABLE "pools" DROP COLUMN "is_public"`);
        await queryRunner.query(`CREATE TYPE "public"."simulation_history_status_enum" AS ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED')`);
        await queryRunner.query(`ALTER TABLE "simulation_history" ADD "status" "public"."simulation_history_status_enum" NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "simulation_history" ADD "started_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "simulation_history" ADD "finished_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "simulation_history" ADD "error_message" text`);
        await queryRunner.query(`ALTER TABLE "simulation_history" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ADD "predicted_home_score" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ADD "predicted_away_score" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ADD "points_earned" integer`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ADD "prediction_type" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "rounds" ALTER COLUMN "is_current" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rounds" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rounds" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "stadiums" ALTER COLUMN "country" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stadiums" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stadiums" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "stadiums"."category" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "players"."category" IS NULL`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "match_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "player_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "match_date"`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "match_date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "group_name"`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "group_name" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "phase"`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "phase" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."category" IS NULL`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "leg" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."leg" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."tie_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."home_aggregate_score" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."away_aggregate_score" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."qualified_team_id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "competitions" DROP COLUMN "logo_url"`);
        await queryRunner.query(`ALTER TABLE "competitions" ADD "logo_url" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "competitions" DROP COLUMN "season"`);
        await queryRunner.query(`ALTER TABLE "competitions" ADD "season" character varying`);
        await queryRunner.query(`COMMENT ON COLUMN "competitions"."category" IS NULL`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "points" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "played" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "won" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "drawn" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "lost" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "goals_for" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "goals_against" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" DROP COLUMN "goal_difference"`);
        await queryRunner.query(`DELETE FROM "public"."typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "database" = $3 AND "schema" = $4 AND "table" = $5`, ["GENERATED_COLUMN","goal_difference","kmiza27_dev","public","competition_teams"]);
        await queryRunner.query(`ALTER TABLE "competition_teams" ADD "goal_difference" integer GENERATED ALWAYS AS (goals_for - goals_against) STORED NOT NULL`);
        await queryRunner.query(`INSERT INTO "public"."typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES ($1, $2, $3, $4, $5, $6)`, ["kmiza27_dev","public","competition_teams","GENERATED_COLUMN","goal_difference","goals_for - goals_against"]);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "titles" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "titles" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "country" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "teams"."category" IS NULL`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "whatsapp_menu_configs" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "whatsapp_menu_configs" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "chatbot_conversations" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chatbot_conversations" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP COLUMN "phone_number"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD "phone_number" character varying NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."delivery_status" RENAME TO "delivery_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notification_deliveries_status_enum" AS ENUM('pending', 'sending', 'delivered', 'failed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "status" TYPE "public"."notification_deliveries_status_enum" USING "status"::"text"::"public"."notification_deliveries_status_enum"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."delivery_status_old"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP COLUMN "whatsapp_message_id"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD "whatsapp_message_id" character varying`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "retry_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "is_sent" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."notification_send_status" RENAME TO "notification_send_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_send_status_enum" AS ENUM('draft', 'queued', 'sending', 'paused', 'completed', 'cancelled', 'failed')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "send_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "send_status" TYPE "public"."notifications_send_status_enum" USING "send_status"::"text"::"public"."notifications_send_status_enum"`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "send_status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."notification_send_status_old"`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "send_status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "total_recipients" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "sent_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "delivered_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "failed_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_phone_number_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone_number"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone_number" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_17d1817f241f10a3dbafb169fd2" UNIQUE ("phone_number")`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_admin" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "welcome_sent" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "whatsapp_status" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."origin" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."role" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "system_settings" ALTER COLUMN "value" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "system_settings" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "system_settings" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "system_settings" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "system_settings" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "simulation_history" DROP CONSTRAINT "PK_8f1905d3e491ddd37344065fccb"`);
        await queryRunner.query(`ALTER TABLE "simulation_history" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "simulation_history" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "simulation_history" ADD CONSTRAINT "PK_8f1905d3e491ddd37344065fccb" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "simulation_history" ALTER COLUMN "results" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "pool_matches" ALTER COLUMN "order_index" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pool_matches" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pool_matches" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pool_participants" ALTER COLUMN "total_points" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pool_participants" ALTER COLUMN "predictions_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pool_participants" ALTER COLUMN "exact_predictions" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pool_participants" ALTER COLUMN "correct_results" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pool_participants" ALTER COLUMN "joined_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pool_participants" ALTER COLUMN "joined_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ALTER COLUMN "predicted_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ALTER COLUMN "predicted_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."pool_type" RENAME TO "pool_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."pools_type_enum" AS ENUM('round', 'custom')`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "type" TYPE "public"."pools_type_enum" USING "type"::"text"::"public"."pools_type_enum"`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "type" SET DEFAULT 'custom'`);
        await queryRunner.query(`DROP TYPE "public"."pool_type_old"`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "type" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."pool_status" RENAME TO "pool_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."pools_status_enum" AS ENUM('draft', 'open', 'closed', 'finished')`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "status" TYPE "public"."pools_status_enum" USING "status"::"text"::"public"."pools_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."pool_status_old"`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "scoring_rules" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "scoring_rules" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "settings" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "international_teams" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "international_teams" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bot_configs" DROP CONSTRAINT "bot_configs_key_key"`);
        await queryRunner.query(`ALTER TABLE "bot_configs" DROP COLUMN "key"`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ADD "key" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ADD CONSTRAINT "UQ_b9dee26d13101a3dae7d232be5c" UNIQUE ("key")`);
        await queryRunner.query(`ALTER TABLE "bot_configs" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "bot_configs" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ADD "type" character varying NOT NULL DEFAULT 'string'`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8433599a38bd08f0e0c647495f" ON "pool_participants" ("pool_id", "user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9b3ed97c8651dc7b8481fbda27" ON "pool_predictions" ("pool_id", "user_id", "match_id") `);
        await queryRunner.query(`ALTER TABLE "competition_teams" ADD CONSTRAINT "UQ_eb3390d51aa9d9bf91a9a535357" UNIQUE ("competition_id", "team_id")`);
        await queryRunner.query(`ALTER TABLE "rounds" ADD CONSTRAINT "FK_a2afd93eef9019af00e5b0750bd" FOREIGN KEY ("competition_id") REFERENCES "competitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_team_history" ADD CONSTRAINT "FK_6718d122f4edf2f52421d8c11f6" FOREIGN KEY ("player_id") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_team_history" ADD CONSTRAINT "FK_7c37895964aa8abdaa37b36416f" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cards" ADD CONSTRAINT "FK_2b450d490a8af8790eb36a8bf64" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cards" ADD CONSTRAINT "FK_fba7c30be9d95ef283b044dcacb" FOREIGN KEY ("player_id") REFERENCES "players"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "FK_2f038c72761fa3e145e65388841" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "FK_7e801455fbac183f51a43b2d099" FOREIGN KEY ("player_id") REFERENCES "players"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "FK_722fcbb0807108f33384bba330f" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" ADD CONSTRAINT "FK_0f4f26a2d7a835aa6083862f0b3" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" ADD CONSTRAINT "FK_4fe688627a700fb47346ef5629f" FOREIGN KEY ("channel_id") REFERENCES "channels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_dc604f895a134adedbbf5bf405d" FOREIGN KEY ("competition_id") REFERENCES "competitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_59709772e5280108190154b7db1" FOREIGN KEY ("round_id") REFERENCES "rounds"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_bb25f11ea6fa78b344a68923769" FOREIGN KEY ("home_team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_e457f057d971e464c1ebf6378c5" FOREIGN KEY ("away_team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_f78a661415b0c75f087c6d026be" FOREIGN KEY ("stadium_id") REFERENCES "stadiums"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_6536ad8c674c5bf7e66f1cb3723" FOREIGN KEY ("qualified_team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ADD CONSTRAINT "FK_56f690272a10f500a7811730172" FOREIGN KEY ("competition_id") REFERENCES "competitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ADD CONSTRAINT "FK_98f4fb4f17e452cd23e9eecfd38" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "FK_5bb52f9ca6581157f87047dcaee" FOREIGN KEY ("stadium_id") REFERENCES "stadiums"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chatbot_conversations" ADD CONSTRAINT "FK_04587ca7b98d66cb1684d38b3b2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD CONSTRAINT "FK_435486b970fffc3e33a7450ee97" FOREIGN KEY ("notification_id") REFERENCES "notifications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD CONSTRAINT "FK_9fcd0b72070848cc484af6bc1ea" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_e74bbfb772dce73fb1de5e27a7e" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_cb0dbc4d8cc4e1a72df06890822" FOREIGN KEY ("favorite_team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "simulation_history" ADD CONSTRAINT "FK_fbafcb31cb54dcaca2fa6418385" FOREIGN KEY ("competition_id") REFERENCES "competitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pool_matches" ADD CONSTRAINT "FK_31f1c7cd512aba8c8e0ac390682" FOREIGN KEY ("pool_id") REFERENCES "pools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pool_matches" ADD CONSTRAINT "FK_3889c8a28c7392cd8715a5651bf" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pool_participants" ADD CONSTRAINT "FK_fd7e27895cfeea1029cc89be3e2" FOREIGN KEY ("pool_id") REFERENCES "pools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pool_participants" ADD CONSTRAINT "FK_6093a5c1be4b930477340bf3504" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ADD CONSTRAINT "FK_7a1753edcd439d1c7590509d34e" FOREIGN KEY ("pool_id") REFERENCES "pools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ADD CONSTRAINT "FK_466d727f381ebf56daf584cf698" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ADD CONSTRAINT "FK_1809aa07c1479205d3cb99bc80e" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pools" ADD CONSTRAINT "FK_f785c1949d532275ac3b9b14a5c" FOREIGN KEY ("round_id") REFERENCES "rounds"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pools" ADD CONSTRAINT "FK_22683eb8f9aa59ec83d231f42d1" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "international_teams" ADD CONSTRAINT "FK_75a4bae0c8e2b6d219d34d8e06d" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "international_teams" DROP CONSTRAINT "FK_75a4bae0c8e2b6d219d34d8e06d"`);
        await queryRunner.query(`ALTER TABLE "pools" DROP CONSTRAINT "FK_22683eb8f9aa59ec83d231f42d1"`);
        await queryRunner.query(`ALTER TABLE "pools" DROP CONSTRAINT "FK_f785c1949d532275ac3b9b14a5c"`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" DROP CONSTRAINT "FK_1809aa07c1479205d3cb99bc80e"`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" DROP CONSTRAINT "FK_466d727f381ebf56daf584cf698"`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" DROP CONSTRAINT "FK_7a1753edcd439d1c7590509d34e"`);
        await queryRunner.query(`ALTER TABLE "pool_participants" DROP CONSTRAINT "FK_6093a5c1be4b930477340bf3504"`);
        await queryRunner.query(`ALTER TABLE "pool_participants" DROP CONSTRAINT "FK_fd7e27895cfeea1029cc89be3e2"`);
        await queryRunner.query(`ALTER TABLE "pool_matches" DROP CONSTRAINT "FK_3889c8a28c7392cd8715a5651bf"`);
        await queryRunner.query(`ALTER TABLE "pool_matches" DROP CONSTRAINT "FK_31f1c7cd512aba8c8e0ac390682"`);
        await queryRunner.query(`ALTER TABLE "simulation_history" DROP CONSTRAINT "FK_fbafcb31cb54dcaca2fa6418385"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_cb0dbc4d8cc4e1a72df06890822"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_e74bbfb772dce73fb1de5e27a7e"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP CONSTRAINT "FK_9fcd0b72070848cc484af6bc1ea"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP CONSTRAINT "FK_435486b970fffc3e33a7450ee97"`);
        await queryRunner.query(`ALTER TABLE "chatbot_conversations" DROP CONSTRAINT "FK_04587ca7b98d66cb1684d38b3b2"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "FK_5bb52f9ca6581157f87047dcaee"`);
        await queryRunner.query(`ALTER TABLE "competition_teams" DROP CONSTRAINT "FK_98f4fb4f17e452cd23e9eecfd38"`);
        await queryRunner.query(`ALTER TABLE "competition_teams" DROP CONSTRAINT "FK_56f690272a10f500a7811730172"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_6536ad8c674c5bf7e66f1cb3723"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_f78a661415b0c75f087c6d026be"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_e457f057d971e464c1ebf6378c5"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_bb25f11ea6fa78b344a68923769"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_59709772e5280108190154b7db1"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_dc604f895a134adedbbf5bf405d"`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" DROP CONSTRAINT "FK_4fe688627a700fb47346ef5629f"`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" DROP CONSTRAINT "FK_0f4f26a2d7a835aa6083862f0b3"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "FK_722fcbb0807108f33384bba330f"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "FK_7e801455fbac183f51a43b2d099"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "FK_2f038c72761fa3e145e65388841"`);
        await queryRunner.query(`ALTER TABLE "cards" DROP CONSTRAINT "FK_fba7c30be9d95ef283b044dcacb"`);
        await queryRunner.query(`ALTER TABLE "cards" DROP CONSTRAINT "FK_2b450d490a8af8790eb36a8bf64"`);
        await queryRunner.query(`ALTER TABLE "player_team_history" DROP CONSTRAINT "FK_7c37895964aa8abdaa37b36416f"`);
        await queryRunner.query(`ALTER TABLE "player_team_history" DROP CONSTRAINT "FK_6718d122f4edf2f52421d8c11f6"`);
        await queryRunner.query(`ALTER TABLE "rounds" DROP CONSTRAINT "FK_a2afd93eef9019af00e5b0750bd"`);
        await queryRunner.query(`ALTER TABLE "competition_teams" DROP CONSTRAINT "UQ_eb3390d51aa9d9bf91a9a535357"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b3ed97c8651dc7b8481fbda27"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8433599a38bd08f0e0c647495f"`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ALTER COLUMN "active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bot_configs" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ADD "type" character varying(50) DEFAULT 'string'`);
        await queryRunner.query(`ALTER TABLE "bot_configs" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ADD "description" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "bot_configs" DROP CONSTRAINT "UQ_b9dee26d13101a3dae7d232be5c"`);
        await queryRunner.query(`ALTER TABLE "bot_configs" DROP COLUMN "key"`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ADD "key" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bot_configs" ADD CONSTRAINT "bot_configs_key_key" UNIQUE ("key")`);
        await queryRunner.query(`ALTER TABLE "international_teams" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "international_teams" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "settings" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "scoring_rules" SET DEFAULT '{"exact_score": 10, "correct_result": 5, "goal_difference": 3}'`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "scoring_rules" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."pool_status_old" AS ENUM('draft', 'open', 'closed', 'finished')`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "status" TYPE "public"."pool_status_old" USING "status"::"text"::"public"."pool_status_old"`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."pools_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."pool_status_old" RENAME TO "pool_status"`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "type" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."pool_type_old" AS ENUM('round', 'custom')`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "type" TYPE "public"."pool_type_old" USING "type"::"text"::"public"."pool_type_old"`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "type" SET DEFAULT 'custom'`);
        await queryRunner.query(`DROP TYPE "public"."pools_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."pool_type_old" RENAME TO "pool_type"`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ALTER COLUMN "predicted_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ALTER COLUMN "predicted_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pool_participants" ALTER COLUMN "joined_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pool_participants" ALTER COLUMN "joined_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pool_participants" ALTER COLUMN "correct_results" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pool_participants" ALTER COLUMN "exact_predictions" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pool_participants" ALTER COLUMN "predictions_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pool_participants" ALTER COLUMN "total_points" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pool_matches" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pool_matches" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pool_matches" ALTER COLUMN "order_index" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "simulation_history" ALTER COLUMN "results" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "simulation_history" DROP CONSTRAINT "PK_8f1905d3e491ddd37344065fccb"`);
        await queryRunner.query(`ALTER TABLE "simulation_history" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "simulation_history" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "simulation_history" ADD CONSTRAINT "PK_8f1905d3e491ddd37344065fccb" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "system_settings" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "system_settings" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "system_settings" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "system_settings" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "system_settings" ALTER COLUMN "value" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."role" IS 'Role do usuário: admin, user, amateur'`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."origin" IS 'Origem do usuário: whatsapp ou site'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "whatsapp_status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "welcome_sent" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_admin" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_17d1817f241f10a3dbafb169fd2"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone_number"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone_number" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_phone_number_key" UNIQUE ("phone_number")`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "failed_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "delivered_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "sent_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "total_recipients" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "send_status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."notification_send_status_old" AS ENUM('draft', 'queued', 'sending', 'paused', 'completed', 'cancelled', 'failed')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "send_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "send_status" TYPE "public"."notification_send_status_old" USING "send_status"::"text"::"public"."notification_send_status_old"`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "send_status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."notifications_send_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_send_status_old" RENAME TO "notification_send_status"`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "is_sent" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "retry_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP COLUMN "whatsapp_message_id"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD "whatsapp_message_id" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."delivery_status_old" AS ENUM('pending', 'sending', 'delivered', 'failed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "status" TYPE "public"."delivery_status_old" USING "status"::"text"::"public"."delivery_status_old"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."notification_deliveries_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."delivery_status_old" RENAME TO "delivery_status"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP COLUMN "phone_number"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD "phone_number" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chatbot_conversations" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "chatbot_conversations" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "whatsapp_menu_configs" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "whatsapp_menu_configs" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "teams"."category" IS 'Categoria do time: professional ou amateur'`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "country" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "titles" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "titles" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`DELETE FROM "public"."typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "database" = $3 AND "schema" = $4 AND "table" = $5`, ["GENERATED_COLUMN","goal_difference","kmiza27_dev","public","competition_teams"]);
        await queryRunner.query(`ALTER TABLE "competition_teams" DROP COLUMN "goal_difference"`);
        await queryRunner.query(`INSERT INTO "public"."typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES ($1, $2, $3, $4, $5, $6)`, ["kmiza27_dev","public","competition_teams","GENERATED_COLUMN","goal_difference",""]);
        await queryRunner.query(`ALTER TABLE "competition_teams" ADD "goal_difference" integer`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "goals_against" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "goals_for" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "lost" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "drawn" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "won" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "played" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ALTER COLUMN "points" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "competitions"."category" IS 'Categoria da competição: professional ou amateur'`);
        await queryRunner.query(`ALTER TABLE "competitions" DROP COLUMN "season"`);
        await queryRunner.query(`ALTER TABLE "competitions" ADD "season" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitions" DROP COLUMN "logo_url"`);
        await queryRunner.query(`ALTER TABLE "competitions" ADD "logo_url" text`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."qualified_team_id" IS 'ID do time que se classificou após o confronto'`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."away_aggregate_score" IS 'Placar agregado do time visitante (soma dos dois jogos)'`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."home_aggregate_score" IS 'Placar agregado do time mandante (soma dos dois jogos)'`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."tie_id" IS 'UUID que agrupa jogos de ida e volta do mesmo confronto'`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."leg" IS 'Indica se é jogo de ida (1) ou volta (2) em confrontos mata-mata'`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "leg" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "matches"."category" IS 'Categoria da partida: professional ou amateur'`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "phase"`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "phase" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "group_name"`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "group_name" character varying(10)`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "match_date"`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "match_date" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "channels" ALTER COLUMN "type" SET DEFAULT 'other'`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "player_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "match_id" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "players"."category" IS 'Categoria do jogador: professional ou amateur'`);
        await queryRunner.query(`COMMENT ON COLUMN "stadiums"."category" IS 'Categoria do estádio: professional ou amateur'`);
        await queryRunner.query(`ALTER TABLE "stadiums" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "stadiums" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stadiums" ALTER COLUMN "country" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rounds" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "rounds" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rounds" ALTER COLUMN "is_current" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" DROP COLUMN "prediction_type"`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" DROP COLUMN "points_earned"`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" DROP COLUMN "predicted_away_score"`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" DROP COLUMN "predicted_home_score"`);
        await queryRunner.query(`ALTER TABLE "simulation_history" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "simulation_history" DROP COLUMN "error_message"`);
        await queryRunner.query(`ALTER TABLE "simulation_history" DROP COLUMN "finished_at"`);
        await queryRunner.query(`ALTER TABLE "simulation_history" DROP COLUMN "started_at"`);
        await queryRunner.query(`ALTER TABLE "simulation_history" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."simulation_history_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pools" ADD "is_public" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "pools" ADD "competition_id" integer`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ADD "score" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ADD "home_score_prediction" integer`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ADD "away_score_prediction" integer`);
        await queryRunner.query(`ALTER TABLE "pool_matches" ADD "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "teams" ADD "stadium" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "competitions" ADD "tiebreaker_criteria" jsonb`);
        await queryRunner.query(`ALTER TABLE "goals" ADD "video_url" text`);
        await queryRunner.query(`ALTER TABLE "goals" ADD "is_own_goal" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "goals" ADD "is_penalty" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ADD CONSTRAINT "pool_predictions_pool_id_user_id_match_id_key" UNIQUE ("pool_id", "user_id", "match_id")`);
        await queryRunner.query(`ALTER TABLE "pool_participants" ADD CONSTRAINT "pool_participants_pool_id_user_id_key" UNIQUE ("pool_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "pool_matches" ADD CONSTRAINT "pool_matches_pool_id_match_id_key" UNIQUE ("pool_id", "match_id")`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ADD CONSTRAINT "competition_teams_competition_id_team_id_key" UNIQUE ("competition_id", "team_id")`);
        await queryRunner.query(`CREATE INDEX "IDX_international_teams_display_order" ON "international_teams" ("display_order") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_international_teams_team_id" ON "international_teams" ("team_id") `);
        await queryRunner.query(`CREATE INDEX "idx_pools_public" ON "pools" ("is_public") `);
        await queryRunner.query(`CREATE INDEX "idx_pools_created_by" ON "pools" ("created_by_user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_pools_type" ON "pools" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_pools_status" ON "pools" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_pool_predictions_match" ON "pool_predictions" ("match_id") `);
        await queryRunner.query(`CREATE INDEX "idx_pool_predictions_user" ON "pool_predictions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_pool_predictions_pool" ON "pool_predictions" ("pool_id") `);
        await queryRunner.query(`CREATE INDEX "idx_pool_participants_score" ON "pool_participants" ("total_points") `);
        await queryRunner.query(`CREATE INDEX "idx_pool_participants_user" ON "pool_participants" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_pool_participants_pool" ON "pool_participants" ("pool_id") `);
        await queryRunner.query(`CREATE INDEX "idx_pool_matches_match" ON "pool_matches" ("match_id") `);
        await queryRunner.query(`CREATE INDEX "idx_pool_matches_pool" ON "pool_matches" ("pool_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_phone" ON "users" ("phone_number") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_user" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_send_status" ON "notifications" ("send_status") `);
        await queryRunner.query(`CREATE INDEX "idx_notification_deliveries_user_id" ON "notification_deliveries" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_notification_deliveries_status" ON "notification_deliveries" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_notification_deliveries_notification_id" ON "notification_deliveries" ("notification_id") `);
        await queryRunner.query(`CREATE INDEX "idx_chatbot_conv_user" ON "chatbot_conversations" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_section_order" ON "whatsapp_menu_configs" ("section_order") `);
        await queryRunner.query(`CREATE INDEX "idx_item_order" ON "whatsapp_menu_configs" ("item_order") `);
        await queryRunner.query(`CREATE INDEX "idx_active" ON "whatsapp_menu_configs" ("active") `);
        await queryRunner.query(`CREATE INDEX "idx_teams_stadium_id" ON "teams" ("stadium_id") `);
        await queryRunner.query(`CREATE INDEX "idx_competition_teams" ON "competition_teams" ("competition_id", "team_id") `);
        await queryRunner.query(`CREATE INDEX "idx_matches_teams" ON "matches" ("away_team_id", "home_team_id") `);
        await queryRunner.query(`CREATE INDEX "idx_matches_status" ON "matches" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_matches_date" ON "matches" ("match_date") `);
        await queryRunner.query(`CREATE INDEX "idx_match_broadcasts_match_id" ON "match_broadcasts" ("match_id") `);
        await queryRunner.query(`ALTER TABLE "international_teams" ADD CONSTRAINT "FK_international_teams_team_id" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pools" ADD CONSTRAINT "pools_competition_id_fkey" FOREIGN KEY ("competition_id") REFERENCES "competitions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pools" ADD CONSTRAINT "pools_round_id_fkey" FOREIGN KEY ("round_id") REFERENCES "rounds"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pools" ADD CONSTRAINT "pools_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ADD CONSTRAINT "pool_predictions_pool_id_fkey" FOREIGN KEY ("pool_id") REFERENCES "pools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ADD CONSTRAINT "pool_predictions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pool_predictions" ADD CONSTRAINT "pool_predictions_match_id_fkey" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pool_participants" ADD CONSTRAINT "pool_participants_pool_id_fkey" FOREIGN KEY ("pool_id") REFERENCES "pools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pool_participants" ADD CONSTRAINT "pool_participants_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pool_matches" ADD CONSTRAINT "pool_matches_pool_id_fkey" FOREIGN KEY ("pool_id") REFERENCES "pools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pool_matches" ADD CONSTRAINT "pool_matches_match_id_fkey" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "simulation_history" ADD CONSTRAINT "FK_fbafcb31cb54dcaca2fa6418385" FOREIGN KEY ("competition_id") REFERENCES "competitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_favorite_team_id_fkey" FOREIGN KEY ("favorite_team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_match_id_fkey" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD CONSTRAINT "fk_notification_deliveries_notification" FOREIGN KEY ("notification_id") REFERENCES "notifications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD CONSTRAINT "fk_notification_deliveries_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chatbot_conversations" ADD CONSTRAINT "chatbot_conversations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "fk_teams_stadium_id" FOREIGN KEY ("stadium_id") REFERENCES "stadiums"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ADD CONSTRAINT "competition_teams_competition_id_fkey" FOREIGN KEY ("competition_id") REFERENCES "competitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_teams" ADD CONSTRAINT "competition_teams_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "fk_matches_qualified_team" FOREIGN KEY ("qualified_team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "matches_away_team_id_fkey" FOREIGN KEY ("away_team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "matches_competition_id_fkey" FOREIGN KEY ("competition_id") REFERENCES "competitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "matches_home_team_id_fkey" FOREIGN KEY ("home_team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "matches_round_id_fkey" FOREIGN KEY ("round_id") REFERENCES "rounds"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "matches_stadium_id_fkey" FOREIGN KEY ("stadium_id") REFERENCES "stadiums"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" ADD CONSTRAINT "match_broadcasts_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "channels"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_broadcasts" ADD CONSTRAINT "match_broadcasts_match_id_fkey" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "fk_goals_player" FOREIGN KEY ("player_id") REFERENCES "players"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "goals_match_id_fkey" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "goals_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cards" ADD CONSTRAINT "fk_cards_match" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cards" ADD CONSTRAINT "fk_cards_player" FOREIGN KEY ("player_id") REFERENCES "players"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_team_history" ADD CONSTRAINT "fk_player_team_history_player" FOREIGN KEY ("player_id") REFERENCES "players"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_team_history" ADD CONSTRAINT "fk_player_team_history_team" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rounds" ADD CONSTRAINT "rounds_competition_id_fkey" FOREIGN KEY ("competition_id") REFERENCES "competitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
